### ISSUE TITLE
Mack Trucks HT SiteMap

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-ht#15]
Hi Team,

The SiteMap page is displaying most of the links that are not there in the repo.

Is there a way to get it updated. Looks like it is the same for all the Sites.

https://www.macktrucks.ht/sitemap.xml
When pages are unpublished, the pages should be removed from the Sitemap. 
Pages designated as "No follow" should be removed from Sitemap also.

**Comment by BeckyMedlin** [comment]
@mollyaljenkins Please add this to the list for refinement.

**Comment by ZoeBeykirch** [comment]
Closing this ticket as it will be solved in https://github.com/hlxsites/vg-macktrucks-com/issues/806 that addresses all MT sites, not just the HT sitemap.
