### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-ht#7]
Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

This is part of the GoLive activities.

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="c3366cf3-ea5b-4446-86d5-9bf537ba9c88" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
`
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>
`
